### ISSUE TITLE
Update index-provider to use new delegated routing HTTP API

### ISSUE THREAD

**Issue by ischasny** [ipni/index-provider#312]
The existing integration is using Reframe which since has been retired in favour of a new HTTP delegated routing specified here: https://github.com/ipfs/specs/pull/337

Update the code to reflect the changes.

**Comment by lidel** [comment]
- afaik Reframe is dead and removed from Kubo. We only use `/routing/v1` from [IPIP-337](https://github.com/ipfs/specs/pull/337)
- By default (`Routing.Type=auto`) Kubo does not publish anything to the hard-coded IPNI at cid.contact
  -  `PUT /routing/v1` was not suppported back then so we've disabled it in https://github.com/ipfs/kubo/pull/9511
- @masih  proposed spec for `PUT /routing/v1` API in[ IPIP-378: Delegated Content Routing PUTs over HTTP API](https://github.com/ipfs/specs/pull/378) a while ago
  - this IPIP is a low priority due to Rhea and things like streaming being way more important  – but let us know if there is reason to prioritize spec and reference implementation in Kubo
